### ISSUE TITLE
Is the Composer package name supposed to be "pmpsdk"?

### ISSUE THREAD

**Issue by abeger** [npr/pmp-php-sdk#33]
The project in GitHub is `phpsdk`, but the package in `composer.json` is `pmpsdk`. Is this a typo or intentional? Either way, it's very confusing.

**Comment by benlk** [comment]
The package's github repository used to be named https://github.com/publicmediaplatform/phpsdk; it's now at https://github.com/npr/pmp-php-sdk after NPR acquired PMP. There is also a Javascript SDK: https://github.com/npr?utf8=%E2%9C%93&q=pmp-+-sdk&type=&language=

The Composer package is https://packagist.org/packages/publicmediaplatform/pmpsdk

It believe it is intentional.

**Comment by scottsmith130** [comment]
There's some cleanup to do with this.  We consolidated all the PMP related repositories into NPR's Github account earlier this year.  That being said, as far as I know the packagist name has always been `pmpsdk`, which I agree is probably not what it should have been called (the `pmp` part is a bit redundant).  

We're going to look into how we might address this.
